name: cifka2019
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cudatoolkit=9.0
  - cudnn=7.3.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.1.1c
  - pip=19.1.1
  - python=3.6.8
  - readline=7.0
  - setuptools=39.1.0
  - sqlite=3.28.0
  - tk=8.6.8
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - cached-property==1.5.1
    - coloredlogs==10.0
    - cycler==0.10.0
    - cython==0.29
    - gast==0.2.2
    - grpcio==1.21.1
    - humanfriendly==4.18
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==3.0.2
    - mido==1.2.9
    - numpy==1.14.5
    - pandas==0.24.1
    - pretty-midi==0.2.8
    - protobuf==3.8.0
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyyaml==5.1
    - scipy==1.2.0
    - six==1.12.0
    - tensorboard==1.10.0
    - tensorflow-gpu==1.10.0
    - termcolor==1.1.0
    - werkzeug==0.15.4
